let products = [
    {
      id: 1,
      name: "Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse",
      category: "women",
      image: "https://github.com/iamjaypal/image-data-project/raw/master/images/product_1.png",
      new_price: 500,
      old_price: 800,
    },
    {
      id: 2,
      name: "Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse",
      category: "women",
      image: "https://github.com/iamjaypal/image-data-project/raw/master/images/product_2.png",
      new_price: 750.0,
      old_price: 1200.0,
    },
    {
      id: 3,
      name: "Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse",
      category: "women",
      image: "https://github.com/iamjaypal/image-data-project/raw/master/images/product_3.png",
      new_price: 600.0,
      old_price: 1000.0,
    },
    {
      id: 4,
      name: "Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse",
      category: "women",
      image: "https://github.com/iamjaypal/image-data-project/raw/master/images/product_4.png",
      new_price: 1000.0,
      old_price: 1500.0,
    },
    {
      id: 5,
      name: "Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse",
      category: "women",
      image: "https://github.com/iamjaypal/image-data-project/raw/master/images/product_5.png",
      new_price: 1350.0,
      old_price: 1200.0,
    },
    {
      id: 6,
      name: "Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse",
      category: "women",
      image: "https://github.com/iamjaypal/image-data-project/raw/master/images/product_6.png",
      new_price: 900.0,
      old_price: 1200.5,
    },
    {
      id: 7,
      name: "Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse",
      category: "women",
      image: "https://github.com/iamjaypal/image-data-project/raw/master/images/product_7.png",
      new_price: 700.0,
      old_price: 1200.0,
    },
    {
      id: 8,
      name: "Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse",
      category: "women",
      image: "https://github.com/iamjaypal/image-data-project/raw/master/images/product_8.png",
      new_price: 1400.0,
      old_price: 1800.0,
    },
    {
      id: 9,
      name: "Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse",
      category: "women",
      image: "https://github.com/iamjaypal/image-data-project/raw/master/images/product_9.png",
      new_price: 1250.0,
      old_price: 1600.0,
    },
    {
      id: 10,
      name: "Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse",
      category: "women",
      image: "https://github.com/iamjaypal/image-data-project/raw/master/images/product_10.png",
      new_price: 1350.0,
      old_price: 1550.0,
    },
    {
      id: 11,
      name: "Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse",
      category: "women",
      image: "https://github.com/iamjaypal/image-data-project/raw/master/images/product_11.png",
      new_price: 1180.0,
      old_price: 1300.0,
    },
    {
      id: 12,
      name: "Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse",
      category: "women",
      image: "https://github.com/iamjaypal/image-data-project/raw/master/images/product_12.png",
      new_price: 1299.0,
      old_price: 1699.0,
    },
    {
      id: 13,
      name: "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket",
      category: "men",
      image: "https://github.com/iamjaypal/image-data-project/raw/master/images/product_13.png",
      new_price: 1199.0,
      old_price: 1499.5,
    },
    {
      id: 14,
      name: "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket",
      category: "men",
      image: "https://github.com/iamjaypal/image-data-project/raw/master/images/product_14.png",
      new_price: 899.0,
      old_price: 1099.5,
    },
    {
      id: 15,
      name: "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket",
      category: "men",
      image: "https://github.com/iamjaypal/image-data-project/raw/master/images/product_15.png",
      new_price: 799.0,
      old_price: 1099.0,
    },
    {
      id: 16,
      name: "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket",
      category: "men",
      image: "https://github.com/iamjaypal/image-data-project/raw/master/images/product_16.png",
      new_price: 1299.0,
      old_price: 1599.0,
    },
    {
      id: 17,
      name: "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket",
      category: "men",
      image: "https://github.com/iamjaypal/image-data-project/raw/master/images/product_17.png",
      new_price: 699.0,
      old_price: 999.0,
    },
    {
      id: 18,
      name: "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket",
      category: "men",
      image: "https://github.com/iamjaypal/image-data-project/raw/master/images/product_18.png",
      new_price: 1699.0,
      old_price: 1999.0,
    },
    {
      id: 19,
      name: "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket",
      category: "men",
      image: "https://github.com/iamjaypal/image-data-project/raw/master/images/product_19.png",
      new_price: 1599.0,
      old_price: 1699.5,
    },
    {
      id: 20,
      name: "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket",
      category: "men",
      image: "https://github.com/iamjaypal/image-data-project/raw/master/images/product_20.png",
      new_price: 1099.0,
      old_price: 1299.0,
    },
    {
      id: 21,
      name: "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket",
      category: "men",
      image: "https://github.com/iamjaypal/image-data-project/raw/master/images/product_21.png",
      new_price: 799.0,
      old_price: 899.0,
    },
    {
      id: 22,
      name: "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket",
      category: "men",
      image: "https://github.com/iamjaypal/image-data-project/raw/master/images/product_22.png",
      new_price: 799.0,
      old_price: 1199.0,
    },
    {
      id: 23,
      name: "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket",
      category: "men",
      image: "https://github.com/iamjaypal/image-data-project/raw/master/images/product_23.png",
      new_price: 999.0,
      old_price: 1299.0,
    },
    {
      id: 24,
      name: "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket",
      category: "men",
      image: "https://github.com/iamjaypal/image-data-project/raw/master/images/product_24.png",
      new_price: 499.0,
      old_price: 899.0,
    },
    {
      id: 25,
      name: "Boys Orange Colourblocked Hooded Sweatshirt",
      category: "kid",
      image: "https://github.com/iamjaypal/image-data-project/raw/master/images/product_25.png",
      new_price: 999.0,
      old_price: 1299.0,
    },
    {
      id: 26,
      name: "Boys Orange Colourblocked Hooded Sweatshirt",
      category: "kid",
      image: "https://github.com/iamjaypal/image-data-project/raw/master/images/product_26.png",
      new_price: 399.0,
      old_price: 499.0,
    },
    {
      id: 27,
      name: "Boys Orange Colourblocked Hooded Sweatshirt",
      category: "kid",
      image: "https://github.com/iamjaypal/image-data-project/raw/master/images/product_27.png",
      new_price: 699.0,
      old_price: 899.5,
    },
    {
      id: 28,
      name: "Boys Orange Colourblocked Hooded Sweatshirt",
      category: "kid",
      image: "https://github.com/iamjaypal/image-data-project/raw/master/images/product_28.png",
      new_price: 799.0,
      old_price: 1299.0,
    },
    {
      id: 29,
      name: "Boys Orange Colourblocked Hooded Sweatshirt",
      category: "kid",
      image: "https://github.com/iamjaypal/image-data-project/raw/master/images/product_29.png",
      new_price: 999.0,
      old_price: 1199.0,
    },
    {
      id: 30,
      name: "Boys Orange Colourblocked Hooded Sweatshirt",
      category: "kid",
      image: "https://github.com/iamjaypal/image-data-project/raw/master/images/product_30.png",
      new_price: 599.0,
      old_price: 799.0,
    },
    {
      id: 31,
      name: "Boys Orange Colourblocked Hooded Sweatshirt",
      category: "kid",
      image: "https://github.com/iamjaypal/image-data-project/raw/master/images/product_31.png",
      new_price: 899.0,
      old_price: 1199.5,
    },
    {
      id: 32,
      name: "Boys Orange Colourblocked Hooded Sweatshirt",
      category: "kid",
      image: "https://github.com/iamjaypal/image-data-project/raw/master/images/product_32.png",
      new_price: 499.0,
      old_price: 799.0,
    },
    {
      id: 33,
      name: "Boys Orange Colourblocked Hooded Sweatshirt",
      category: "kid",
      image: "https://github.com/iamjaypal/image-data-project/raw/master/images/product_33.png",
      new_price: 1299.0,
      old_price: 1499.0,
    },
    {
      id: 34,
      name: "Boys Orange Colourblocked Hooded Sweatshirt",
      category: "kid",
      image: "https://github.com/iamjaypal/image-data-project/raw/master/images/product_34.png",
      new_price: 499.0,
      old_price: 699.0,
    },
    {
      id: 35,
      name: "Boys Orange Colourblocked Hooded Sweatshirt",
      category: "kid",
      image: "https://github.com/iamjaypal/image-data-project/raw/master/images/product_35.png",
      new_price: 599.0,
      old_price: 999.0,
    },
    {
      id: 36,
      name: "Boys Orange Colourblocked Hooded Sweatshirt",
      category: "kid",
      image: "https://github.com/iamjaypal/image-data-project/raw/master/images/product_36.png",
      new_price: 1499.0,
      old_price: 1999.0,
    },
  ];
  
  export default all_product;
